### ISSUE TITLE
Change component name when production build

### ISSUE THREAD

**Issue by dungsil** [nuxt-community/nuxt-property-decorator#70]
When registering a component with plugin, if you register as `Vue.component(MyComponent.name, MyComponent)`, the component name will be different during production build.

 - development build
![#](https://i.imgur.com/SRK5mX3.png)

 - production build
![#](https://i.imgur.com/nR7gw6m.png)

## link
 - source code & development build : https://codesandbox.io/s/y5046?file=/plugins/global.ts
 - production build: https://nuxt-property-decorator-issue.firefanda.now.sh/

**Comment by husayt** [comment]
This library is just a Nuxt wrapper over Vue-class-component. As such any behavour specifics need to be checked on their forum.

On my side, I could guess that difference in behavior is due to js minification which happens in prod build. Logic which is based on class names is very error prone, as class names change on build. 

To have more control, one could add explicit class name:
```
@Component({ name: "Privet" })
```

I did change an example above, to demonstrate that here:
https://codesandbox.io/s/nuxt-issue-forked-zfkkq

Also, probably all this is really unnecessary since Nuxt has components auto discovery now with `components : true` flag.

I will close this issue here. If still any question check with vue-class-component team.
